import Head from 'next/head'
import styles from '../styles/Home.module.css'

import React, {useState, useEffect, createElement} from 'react'
import Link from 'next/Link'
import { motion } from 'framer-motion'

import axios from 'axios'

export default function Home() {
  const [nasdaqList, setNasdaqList] = useState([]);
  useEffect(() => {
    axios.get('http://localhost:3001/nasdaq').then((response) => {
        setNasdaqList(response.data)
    })
  }, []); 

  const [ticker, setTicker] = useState([]);
  useEffect(() => {
    axios.get('http://localhost:3001/read').then((response) => {
      setTicker(response.data);
    })
  }, [])

  //trending
  const [trending, setTrending] = useState([]);
  useEffect(() => {
    axios.post('http://localhost:3001/trending').then((response) => {
      setTrending(response.data);
    })
  }, []); 
  
  for (var i = 0; i < trending.length; ++i) {
    if (trending[i].selftext === "") { trending.splice(i, 1); console.log("empty string found") }
  }

  return (  
    <div className={styles.container}>
      <Head>
        <title>wsb-tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main>
        <div>
          <h1 className={styles.title}>
            Welcome to <a href="/">WallStatusBets.io!</a>
          </h1>

          <p className={styles.description}>
            What do the people of the {' '}
            <code className={styles.code}>r/wallstreetbets</code>
            {' '} think?
          </p>
          <div className={styles.start}>
            <Link href="/searchresult">Start!</Link>
          </div>
        </div>

        <h1 className={styles.trendingTitle}>Trending</h1>

        <div className={styles.row}>
          
          <motion.div className={styles.trending}
            initial={{ x: '-100vw' }}
            animate={{ x: 0 }}
            transition={{ type: 'spring', duration: 1, bounce: 0.3 }}
          >
            <div>
              <p id="wsbtrending" className={styles.description}><code className={styles.code}>r/wallstreetbets</code></p>
                {/* {snoowrapCount} */}
                {trending.map((val, key) => {
                  if (key != 0) {
                    return (
                      <p key={key} id={styles.list}>{key}. {val.selftext}</p>
                    )
                  }
                })}
            </div>
          </motion.div>

          <motion.div className={styles.wsb}
            initial={{ x: '100vw' }}
            animate={{ x: 0 }}
            transition={{ type: 'spring', duration: 1, bounce: 0.3 }}
          >
            <p className={styles.description}><code className={styles.code}>WallStatusBets.io</code></p>
                {ticker.map((val, key) => {
                    return (
                      <p key={key} id={styles.ticker}>{key+1}. {val.ticker} - {val.count} searches</p>
                    )
                })}
          </motion.div>
        </div>
      </main>
      


      <footer className={styles.footer}>
        <a className={styles.github}
          href="https://github.com/minsooerickim"
          target="_blank"
          rel="noopener noreferrer"
        >
        Powered by &nbsp;<span>Minsoo Kim</span>
        </a>
      </footer>
    </div>
  )
}
