import React from 'react'
import Head from 'next/head'
import { motion } from "framer-motion";

import Ticker from '../components/Ticker'
import Loading from '../components/Loading'

import styles from '../styles/searchresult.module.css'

export default function searchResult() {
    return (  
        <div className={styles.container}>
          <Head>
            <title>wsb-tracker</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
    
          <main>
            <div>
              <motion.div
                initial={{ x: '-100vw' }}
                animate={{ x: 0 }}
                transition={{ type: 'spring', duration: 1, bounce: 0.3 }}
              >
                <h1 className={styles.title}>
                  Welcome to <a href="/"> WallStatusBets.io!</a>
                </h1>
              </motion.div>
              
              <div id="disappear">
                <motion.div
                  initial={{ x: '100vw' }}
                  animate={{ x: 0 }}
                  transition={{ type: 'spring', duration: 1, bounce: 0.3 }}
                >
                  <p className={styles.description}>
                    What do the people of the {' '}
                    <code className={styles.code}>r/wallstreetbets</code>
                    {' '} think?
                  </p>
                
                <div className={styles.start}>
                  <Ticker/>
                </div>
                </motion.div>
              </div>
            </div>
            <Loading/>
          </main>
          
    
    
          <footer className={styles.footer}>
            <a className={styles.github}
              href="https://github.com/minsooerickim"
              target="_blank"
              rel="noopener noreferrer"
            >
            Powered by &nbsp;<span>Minsoo Kim</span>
            </a>
          </footer>
        </div>
    )
}

